from fastapi import HTTPException

ORDER_STATES=['CREATED','AGGREGATING','MATCHED','PICKUP_ASSIGNED','PICKED_UP','AT_COLLECTION','INSPECTED','PACKED','AT_PACKAGE_CENTRE','AT_HUB','OUT_FOR_DELIVERY','DELIVERED','CANCELLED']
ALLOWED={
'CREATED':{'AGGREGATING','CANCELLED'},'AGGREGATING':{'MATCHED','CANCELLED'},'MATCHED':{'PICKUP_ASSIGNED','CANCELLED'},'PICKUP_ASSIGNED':{'PICKED_UP','CANCELLED'},'PICKED_UP':{'AT_COLLECTION'},'AT_COLLECTION':{'INSPECTED'},'INSPECTED':{'PACKED'},'PACKED':{'AT_PACKAGE_CENTRE'},'AT_PACKAGE_CENTRE':{'AT_HUB'},'AT_HUB':{'OUT_FOR_DELIVERY'},'OUT_FOR_DELIVERY':{'DELIVERED'},'DELIVERED':set(),'CANCELLED':set()}

def transition(order, new_status):
    if new_status not in ALLOWED.get(order.status,set()):
        raise HTTPException(400, f'Invalid transition {order.status} -> {new_status}')
    order.status=new_status
